server.forward-headers-strategy=framework

spring.application.name=sniffy

spring.session.jdbc.initialize-schema=always

spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.data.web.pageable.one-indexed-parameters=true

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Hibernate가 테이블을 생성한 뒤에 data.sql 실행 (초기 데이터)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

mybatis.mapper-locations=classpath:mapper/**/**.xml
mybatis.configuration.map-underscore-to-camel-case=true

# 공공데이터 포털 API 키 (Encoding)
data.go.kr.api.key=${DATA_GO_KR_API_KEY}

# Web Push 설정
vapid.public-key=${VAPID_PUBLIC_KEY}
vapid.private-key=${VAPID_PRIVATE_KEY}
vapid.subject=${VAPID_SUBJECT}